site_name: Komoju-WooCommerce Plugin Docs
site_url: "https://tech.degica.com/komoju-woocommerce/"
theme:
  name: material
  palette:
    scheme: default
    primary: indigo
    accent: pink
  font:
    text: Roboto
    code: Roboto Mono

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/example
      name: GitHub

nav:
  - UserGuide: user_guide/getting_started.md
  - DeveloperGuide: 
    - Setup: developer_guide/dev_setup.md
    - UploadPlugin: developer_guide/uploading_to_wordpress_store.md
  - Komoju: 
    - Overview: index.md
    - Benefits: komoju/benefits.md
    - Features: komoju/features.md

plugins:
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          name: English
          build: true
          site_name: KOMOJU WooCommerce Plugin Docs
        - locale: ja
          default: true
          name: 日本語
          build: true
          site_name: KOMOJU WooCommerce プラグイン ドキュメント
          nav_translations:
            Home: ホーム
            Komoju: KOMOJU
            Overview: 概要
            Benefits: メリット
            Features: 機能
            UserGuide: ユーザーマニュアル
            DeveloperGuide: 開発者マニュアル
            Guide: はじめに
            Setup: セットアップ
            UploadPlugin: プラグインのアップロード

