name: Deploy
on:
  push:
    tags:
      - "*"

jobs:
  tag:
    name: Deploy Wordpress Plugin
    runs-on: ubuntu-latest
    steps:
    - name: setup
      uses: actions/checkout@master
    - name: Install SVN
      run: sudo apt-get update && sudo apt-get install -y subversion
    - name: deploy plugin
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SLUG: komoju-japanese-payments
