name: Deploy Docs to GitHub Pages
on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install mkdocs mkdocs-material mkdocs-static-i18n

      - name: Build docs
        run: mkdocs build

      - name: Deploy to gh-pages using PAT
        run: |
          cd site
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote add origin "https://${{ secrets.DOCS_DEPLOY_TOKEN }}@github.com/degica/komoju-woocommerce.git"
          git checkout -b gh-pages
          git add .
          git commit -m "Deploy docs"
          git push origin gh-pages --force